version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: betslip-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-betslip_converter}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./deployment/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - betslip-network
    command: mongod --auth

  # Redis Cache (optional)
  redis:
    image: redis:7.2-alpine
    container_name: betslip-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - betslip-network
    command: redis-server --appendonly yes

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betslip-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/betslip_converter?authSource=admin
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ODDS_API_KEY=${ODDS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      - BROWSER_HEADLESS=true
      - BROWSER_TIMEOUT=30000
      - USE_PARALLEL_PROCESSING=true
      - MAX_CONCURRENT_BROWSERS=3
      - MAX_MEMORY_MB=2048
    depends_on:
      - mongodb
      - redis
    networks:
      - betslip-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "server/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: betslip-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - betslip-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  betslip-network:
    driver: bridge